[package]
name = "rust_pll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
num = "0.4.1"
pad = "0.1.6"
log = "0.4.17"
env_logger = "0.7"
